name: "Install"
description: "Sets up Node.js and runs install"

runs:
  using: composite

  steps:
    - name: Cache node_modules
      uses: actions/cache@v3
      id: npm-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      shell: bash
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm ci
