name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: 🏗 Build application
        run: npm run build

  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: 🔬 Lint
        run: npm run lint

  typecheck:
    name: TypeScript
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: 🔎 Type check
        run: npm run typecheck
